//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.01 at 04:46:50 PM CET 
//


package monpkg;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the monpkg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: monpkg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Responsable }
     * 
     */
    public Responsable createResponsable() {
        return new Responsable();
    }

    /**
     * Create an instance of {@link Intervenant }
     * 
     */
    public Intervenant createIntervenant() {
        return new Intervenant();
    }

    /**
     * Create an instance of {@link Unite }
     * 
     */
    public Unite createUnite() {
        return new Unite();
    }

    /**
     * Create an instance of {@link RefIntervenant }
     * 
     */
    public RefIntervenant createRefIntervenant() {
        return new RefIntervenant();
    }

    /**
     * Create an instance of {@link Semestre }
     * 
     */
    public Semestre createSemestre() {
        return new Semestre();
    }

    /**
     * Create an instance of {@link RefUnite }
     * 
     */
    public RefUnite createRefUnite() {
        return new RefUnite();
    }

    /**
     * Create an instance of {@link NomRes }
     * 
     */
    public NomRes createNomRes() {
        return new NomRes();
    }

    /**
     * Create an instance of {@link Master }
     * 
     */
    public Master createMaster() {
        return new Master();
    }

    /**
     * Create an instance of {@link Parcours }
     * 
     */
    public Parcours createParcours() {
        return new Parcours();
    }

    /**
     * Create an instance of {@link Debouche }
     * 
     */
    public Debouche createDebouche() {
        return new Debouche();
    }

    /**
     * Create an instance of {@link IdUE }
     * 
     */
    public IdUE createIdUE() {
        return new IdUE();
    }

}
